### PR TITLE
add line to fix infinite loop in terminal setup

### PR DESCRIPTION
**Pull request by 4t0m**

### CODE REVIEW

**Comment by wolverdude** [comment]
This shouldn't create an infinite loop. The only reason this might happen is if they're sourcing `.bash_profile` or `.bashrc` from their `.profile`.  That's the real problem.

**Comment by wolverdude** [comment]
That's not exactly what I meant. I mean _you_ remove the line from `.bashrc`.

**Comment by 4t0m** [comment]
Ah, sorry.  So are there linux-only dotfiles, or is that line unnecessary for apple computers as well?

**Comment by wolverdude** [comment]
Correct. It was referenced in the initial dotfiles that I inherited. It seems that I misunderstood what `.profile` was or why it was included.

**Pull request closed without merging**
