### PR TITLE
IN-10 Add timestamp to bash history

### PR DESCRIPTION
**Pull request by niartenyaw**

### CODE REVIEW

**Comment by wolverdude** [comment]
Ooh, that looks cool! What's the reason for adding it?

**Comment by niartenyaw** [comment]
We caught a student cheating on an assessment this week. It would have been really helpful to know the times of their bash commands, but luckily the order of commands was incriminating enough. 

And it's awesome!

**Comment by wolverdude** [comment]
Aaah. _That_ is useful knowledge. The one bit of reticence I have about this is that I've tried to keep these as vanilla as possible so that we're not installing a bunch of weird, idiosyncratic configurations on people's machines that they won't understand. I'm also assuming that this change won't impact the way the terminal displays the history to the user?

**Comment by niartenyaw** [comment]
It does affect the display slightly.

They now have timestamps at the beginning.

screen shot 2018-01-04 at 11 31 58 am

It also adds timestamps from epoch to the `.bash_history`

screen shot 2018-01-04 at 11 33 28 am

**Comment by wolverdude** [comment]
Okay, as long as ctrl-r and up/down are unaffected, I'm good with the merge.

**Comment by niartenyaw** [comment]
Just checked on my machine and they are unaffected.

**Pull request merged**
